<?php
    $env = $services->get('env');
    $defaults = $services->get('defaults');
    $urler = $services->get('urler');
    $request = $services->get('request');
    $order = ($request->query->get('order') == 'count') ? 'count' : 'alpha';
?>

<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title><?php echo $defaults->getItem('siteTitle'); ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        <link rel="stylesheet" href="<?php echo $env->getMediaPath(); ?>/styles/site/css/frontend/global.css">
        <script src="<?php echo $env->getVendorMediaPath(); ?>/modernizr/modernizr-2.5.3.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
    
        <div class="top">
            <?php
                echo $view->render(
                    'frontend/_partials/top.phtml',
                    array(
                        'env' => $env,
                        'urler' => $urler,
                        'defaults' => $defaults,
                        'request' => $request
                    )
                );
            ?>
        </div>
    
        <div role="main" class="content tag-index-content">
            <h1 class="main-title">Tags</h1>
            
            <div class="sort">
                sort by <a href="?order=alpha">alpha</a>
                or by <a href="?order=count">count</a>
            </div>
            
            <?php if($tags->count()): ?>
                <ul class="scribbled-tags">
                    <?php if($order == 'alpha'): ?>
                        <?php $tags->sort(false); ?>
                        <?php foreach($tags as $key => $tag): ?>
                            <li>
                                <a href="<?php echo $urler->generate('frontendScribbleTag', array('tags' => $tag)); ?>" class="scribbled-tag">
                                    <?php echo $tag; ?>
                                    <span><?php echo $tagCounts->get($key); ?></span>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <?php $tagCounts->sort(true); ?>
                        <?php foreach($tagCounts as $key => $count): ?>
                            <li>
                                <a href="<?php echo $urler->generate('frontendScribbleTag', array('tags' => $tags->get($key))); ?>" class="scribbled-tag">
                                    <?php echo $tags->get($key); ?>
                                    <span><?php echo $count; ?></span>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </ul>
            <?php endif; ?>
        </div>
    
        <div class="bottom">
            <?php
                echo $view->render(
                    'frontend/_partials/bottom.phtml',
                    array(
                        'env' => $env,
                        'urler' => $urler
                    )
                );
            ?>
        </div>

        <?php echo $view->render('frontend/_partials/analytics.phtml', array('id' => $services->get('google')->getItem('analyticsId'))); ?>
    </body>
</html>