<?php
    $env = $services->get('env');
    $defaults = $services->get('defaults');
    $facebook = $services->get('facebook');
    $urler = $services->get('urler');
    $request = $services->get('request');
    $canonicalUrl = $urler->generate('frontendScribbleDetail', array('slug' => $scribble->getSlug()), true);

    // final massage of scribble content
    // replace some php scribble getters with their value
    $find = array(
        '/&lt;\?php echo \$scribble-&gt;getPath\(\); \?&gt;/',
        '/&lt;\?php echo \$env-&gt;getBasePath\(\); \?&gt;/',
        '/&lt;\?php echo \$env-&gt;getVendorMediaPath\(\); \?&gt;/'
    );

    $replace = array(
        $scribble->getPath(),
        $env->getBasePath(),
        $env->getVendorMediaPath()
    );

    $scribbleContent = preg_replace($find, $replace, $scribble->getContent());
?>

<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title><?php echo $scribble->getTitle(); ?></title>
        <meta name="description" content="<?php echo implode(' ', $scribble->getTags()->toArray()); ?>">
        <meta name="description" content="<?php echo htmlspecialchars($scribble->getLede(), ENT_COMPAT); ?>">
        <meta name="viewport" content="width=device-width">
        <link rel="stylesheet" href="<?php echo $env->getMediaPath(); ?>/styles/site/css/frontend/global.css">
        <?php echo $view->render('frontend/_partials/modernizr.phtml', array('vendorMediaPath' => $env->getVendorMediaPath())); ?>
        
        <?php if($facebook->getItem("appId")): ?>
            <meta property="fb:app_id" content="<?php echo $defaults->getItem("facebookAppId"); ?>" />
            <meta property="fb:admins" content="<?php echo $defaults->getItem("facebookAdmins"); ?>" />
            <meta property="og:url" content="<?php echo $canonicalUrl; ?>" />
            <meta property="og:title" content="<?php echo $scribble->getTitle(); ?>" />

            <?php if($scribble->getImage()): ?>
                <meta property="og:image" content="http://<?php echo $_SERVER['HTTP_HOST']; ?><?php echo $scribble->getPath(); ?>/<?php echo $scribble->getImage(); ?>" />
            <?php else: ?>
                <meta property="og:image" content="<?php echo $defaults->getItem('scribbleImage'); ?>" />
            <?php endif; ?>

            <meta property="og:type" content="article" />
            <meta property="og:description" content="<?php echo $scribble->getLede(); ?>" />
            <meta property="og:site_name" content="<?php echo $_SERVER["HTTP_HOST"]; ?>" />
        <?php endif; ?>
        <?php /*
        <link rel="stylesheet" href="http://yandex.st/highlightjs/6.2/styles/solarized_dark.min.css">
        <script src="http://yandex.st/highlightjs/6.2/highlight.min.js"></script>
        
        <script type="text/javascript">
            //hljs.tabReplace = '    ';
            hljs.initHighlightingOnLoad();
        </script>
        */ ?>
    </head>
    <body>
        <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
    
        <div class="top">
            <?php
                echo $view->render(
                    'frontend/_partials/top.phtml',
                    array(
                        'env' => $env,
                        'urler' => $urler,
                        'defaults' => $defaults,
                        'request' => $request
                    )
                );
            ?>
        </div>
    
        <div role="main" class="content scribble-detail-content">
            <article class="full-scribble">
                <?php if(!$scribble->isPublished()): ?>
                    <div class="scribbled-not-published">Not published</div>
                <?php endif; ?>
                
                <h1 class="main-title"><?php echo $scribble->getTitle(); ?></h1>
            
                <div class="scribbled-scribble-data">
                    <?php echo $scribbleContent; ?>
                </div>
                
                <div class="scribbled-scribble-meta">
                    <time datetime="<?php echo $scribble->getCreated()->format('Y-m-d'); ?>" class="created">
                        <?php echo $scribble->getCreated()->format($defaults->getItem('dateFormat')); ?>
                    </time>
                    
                    <?php if($scribble->getCreated() != $scribble->getModified()): ?>
                        <time datetime="<?php echo $scribble->getModified()->format('Y-m-d'); ?>" class="modified">
                            <?php echo $scribble->getModified()->format($defaults->getItem('dateFormat')); ?> (updated)
                        </time>
                    <?php endif; ?>
                    
                    <?php if($scribble->getTags()->count()): ?>
                        <?php if($scribble->getTags()): ?>
                            <ul class="scribbled-tags">
                                <?php foreach($scribble->getTags() as $tag): ?>
                                    <li>
                                        <a href="<?php echo $urler->generate('frontendScribbleTag', array('tags' => $tag)); ?>" class="scribbled-tag">
                                            <?php echo $tag; ?>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            </article>
            
            <?php if($defaults->getItem('enableSocialPlugins', false)): ?>
                <div class="facebook">
                    <?php if($facebook->getItem("appId")): ?>
                        <div class="fb-like" data-href="<?php echo $canonicalUrl; ?>" data-layout="standard" data-send="true" data-width="420" data-show-faces="true"></div><br />
                        <div class="fb-comments" data-href="<?php echo $canonicalUrl; ?>" data-num-posts="100" data-width="420"></div><br />
                        <div id="fb-root"></div>

                        <script>
                            window.fbAsyncInit = function() {
                                FB.init({
                                    appId: '<?php echo $facebook->getItem("appId"); ?>',
                                    channelUrl: '<?php echo $urler->generate("facebookChannelIndex", array(), true); ?>',
                                    status: true, // check login status
                                    cookie: true, // enable cookies to allow the server to access the session
                                    xfbml: true  // parse XFBML
                                });
                            };

                            (function(d){
                                var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
                                if (d.getElementById(id)) {return;}
                                js = d.createElement('script'); js.id = id; js.async = true;
                                js.src = "//connect.facebook.net/en_US/all.js";
                                ref.parentNode.insertBefore(js, ref);
                            }(document));
                        </script>
                    <?php endif; ?>
                </div>
                
                <div class="twitter-plus-one">
                    <a href="https://twitter.com/share" class="twitter-share-button" data-size="large">Tweet</a>
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

                    <g:plusone annotation="inline" width="160" href="<?php echo $canonicalUrl; ?>"></g:plusone>

                    <script type="text/javascript">
                        (function() {
                            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                            po.src = 'https://apis.google.com/js/plusone.js';
                            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                        })();
                    </script>
                </div>
            <?php endif; ?>
        </div>
    
        <div class="bottom">
            <?php
                echo $view->render(
                    'frontend/_partials/bottom.phtml',
                    array(
                        'env' => $env,
                        'urler' => $urler
                    )
                );
            ?>
        </div>

        <?php echo $view->render('frontend/_partials/analytics.phtml', array('id' => $services->get('google')->getItem('analyticsId'))); ?>
    </body>
</html>