<?php
    $env = $services->get('env');
    $defaults = $services->get('defaults');
    $urler = $services->get('urler');
    $request = $services->get('request');

    $feedUrl
        = ($defaults->getItem('siteFeedUrl'))
        ? $defaults->getItem('siteFeedUrl')
        : $urler->generate('feedScribbleIndex', array(), true)
    ;
?>

<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title><?php echo $defaults->getItem('siteTitle'); ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        <link rel="alternate" type="application/atom+xml" title="<?php echo $defaults->getItem('siteTitle'); ?>" href="<?php echo $feedUrl; ?>" />
        <link rel="stylesheet" href="<?php echo $env->getMediaPath(); ?>/styles/site/css/frontend/global.css">
        <?php echo $view->render('frontend/_partials/modernizr.phtml', array('vendorMediaPath' => $env->getVendorMediaPath())); ?>
    </head>
    <body>
        <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
        
        <div class="top">
            <?php
                echo $view->render(
                    'frontend/_partials/top.phtml',
                    array(
                        'env' => $env,
                        'urler' => $urler,
                        'defaults' => $defaults,
                        'request' => $request
                    )
                );
            ?>
        </div>
        
        <div role="main" class="content scribble-index-content">
            <?php if(count($scribbles->getCriteria()->getTags())): ?>
                <div class="scribbled-breadcrumbs">
                    <h2>Selected tags <a href="<?php echo $urler->generate('frontendScribbleIndex'); ?>">Clear</a></h2>
                    
                    <ul class="scribbled-tags">
                        <?php $tagStack = array(); ?>
                        <?php foreach($scribbles->getCriteria()->getTags() as $tag): ?>
                            <?php /* click a tag to go to that level and stay in hierarchy */?>
                            <?php /*
                            <?php $tagStack[] = $tag; ?>
                            <li>
                                <a href="<?php echo $urler->generate('frontendScribbleTag', array('tags' => implode('/', $tagStack))); ?>" class="tag">
                                    <?php echo $tag; ?>
                                </a>
                            </li>
                            */ ?>
                            <li>
                                <?php /* click a tag to move it to the top */ ?>
                                <a href="<?php echo $urler->generate('frontendScribbleTag', array('tags' => $tag)); ?>" class="scribbled-tag">
                                    <?php echo $tag; ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                    
                    <?php if($scribbles->getRelatedTags()->count() && $scribbles->getPaginator()->getNumItems() > 1): ?>
                        <div class="scribbled-related-tags">
                            <h2>Related Tags</h2>
                            
                            <ul class="scribbled-tags">
                                <?php foreach($scribbles->getRelatedTags() as $key => $tag): ?>
                                    <li>
                                        <?php
                                            $t = $scribbles->getCriteria()->getTags()->toArray();
                                            $t[$key] = $tag;
                                        ?>
                                        <a href="<?php echo $urler->generate('frontendScribbleTag', array('tags' => implode('/', $t))); ?>" class="scribbled-tag">
                                            <?php echo $tag; ?>
                                            <span><?php echo $scribbles->getRelatedTagCounts()->get($key); ?></span>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>

            <?php if(!$scribbles->getScribbles()->count()): ?>
                <div class="scribbled-no-scribbles">
                    <?php if(count($scribbles->getCriteria()->getTags()) && $scribbles->getCriteria()->getFind()): ?>
                        Sorry, no scribbles match the term "<?php echo $scribbles->getCriteria()->getFind(); ?>" and the <?php echo (count($scribbles->getCriteria()->getTags()) > 1) ? 'tags' : 'tag' ?> "<?php echo implode('" and "', $scribbles->getCriteria()->getTags()->toArray()); ?>"
                    <?php elseif($scribbles->getCriteria()->getFind()): ?>
                        Sorry, no scribbles match the term "<?php echo $scribbles->getCriteria()->getFind(); ?>"
                    <?php elseif(count($scribbles->getCriteria()->getTags())): ?>
                        Sorry, no scribbles match the <?php echo (count($scribbles->getCriteria()->getTags()) > 1) ? 'tags' : 'tag' ?> "<?php echo implode('" and "', $scribbles->getCriteria()->getTags()->toArray()); ?>"
                    <?php endif; ?>
                    <br />
                    <a href="<?php echo $urler->generate('frontendScribbleIndex'); ?>">Back to overview</a>
                </div>
            <?php else: ?>
                <div class="scribbled-scribbles">
                    <ul class="scribbles">
                        <?php foreach($scribbles->getScribbles() as $scribble): ?>
                            <li class="scribble">
                                <article class="scribbled-scribble-preview">
                                    <?php if(!$scribble->isPublished()): ?>
                                        <div class="scribbled-not-published">Not published</div>
                                    <?php endif; ?>
                                    
                                    <h1>
                                        <a href="<?php echo $urler->generate('frontendScribbleDetail', array('slug' => $scribble->getSlug())); ?>">
                                            <?php echo $scribble->getTitle(); ?>
                                        </a>
                                    </h1>
                                    
                                    <?php if($scribble->getLede()): ?>
                                        <p class="lede"><?php echo $scribble->getLede(); ?></p>
                                    <?php endif; ?>
                                    
                                    <div class="scribbled-scribble-meta">
                                        <time datetime="<?php echo $scribble->getCreated()->format('Y-m-d'); ?>">
                                            <?php echo $scribble->getCreated()->format($defaults->getItem('dateFormat')); ?>
                                        </time>
                                        
                                        <?php if($scribble->getTags()): ?>
                                            <ul class="scribbled-tags">
                                                <?php foreach($scribble->getTags() as $tag): ?>
                                                    <li>
                                                        <a href="<?php echo $urler->generate('frontendScribbleTag', array('tags' => $tag)); ?>" class="scribbled-tag">
                                                            <?php echo $tag; ?>
                                                        </a>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        <?php endif; ?>
                                    </div>
                                </article>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                    
                    <?php if($scribbles->getPaginator()->getNumPages() > 1): ?>
                        <div class="scribbled-paginator">
                            <?php
                                echo $view->render(
                                    'frontend/_partials/paginator.phtml',
                                    array(
                                        'paginator' => $scribbles->getPaginator()
                                    )
                                );
                            ?>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
    
        <div class="bottom">
            <?php
                echo $view->render(
                    'frontend/_partials/bottom.phtml',
                    array(
                        'env' => $env,
                        'urler' => $urler
                    )
                );
            ?>
        </div>

        <?php echo $view->render('frontend/_partials/analytics.phtml', array('id' => $services->get('google')->getItem('analyticsId'))); ?>
    </body>
</html>