<?php
    $env = $services->get('env');
    $defaults = $services->get('defaults');
    $urler = $services->get('urler');
    $request = $services->get('request');
    
    $title
        = ($exception->getStatusCode() == 404)
        ? 'Page Not Found'
        : 'Internal Server Error'
    ;
?>

<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title><?php echo $title; ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        <link rel="stylesheet" href="<?php echo $env->getMediaPath(); ?>/styles/site/css/frontend/global.css">
        <?php echo $view->render('frontend/_partials/modernizr.phtml', array('vendorMediaPath' => $env->getVendorMediaPath())); ?>
    </head>
    <body>
        <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
    
        <div class="top">
            <?php
                echo $view->render(
                    'frontend/_partials/top.phtml',
                    array(
                        'env' => $env,
                        'urler' => $urler,
                        'defaults' => $defaults,
                        'request' => $request
                    )
                );
            ?>
        </div>
    
        <div role="main" class="content">
            <h1 class="main-title"><?php echo $title; ?></h1>

            <?php if($exception->getStatusCode() == 404): ?>
                <p>Sorry, but the page you were trying to view does not exist.</p>
            <?php elseif($exception->getStatusCode() == 500): ?>
                <p>Sorry, something went wrong</p>
            <?php endif; ?>
            
            <?php if($env->debug()): ?>
                <div class="exception">
                    <?php /*echo preg_replace('/(#\d+)/', "<br />$1", $exception->getTraceAsString());*/ ?>
                    <?php echo $exception->getMessage(); ?><br />
                    <?php echo get_class($exception); ?>
                    <?php
                        #var_dump($exception);
                    ?>
                </div>
            <?php endif; ?>
        </div>
    
        <div class="bottom">
            <?php
                echo $view->render(
                    'frontend/_partials/bottom.phtml',
                    array(
                        'env' => $env,
                        'urler' => $urler
                    )
                );
            ?>
        </div>

        <?php echo $view->render('frontend/_partials/analytics.phtml', array('id' => $services->get('google')->getItem('analyticsId'))); ?>
    </body>
</html>